// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartResumeAnalyzerAgent.Infrastructure.Persistence;

#nullable disable

namespace SmartResumeAnalyzerAgent.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260319121018_Add_Entities_resume")]
    partial class Add_Entities_resume
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartResumeAnalyzerAgent.Domain.Entities.Resume", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExtractedText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("TargetJobRole")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("resumes", (string)null);
                });

            modelBuilder.Entity("SmartResumeAnalyzerAgent.Domain.Entities.ResumeAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<List<string>>("MatchedJobRoles")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<List<string>>("MissingSkills")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("OverallFeedback")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawAiResponse")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ResumeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<List<string>>("Skills")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<List<string>>("Suggestions")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MissingSkills");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("MissingSkills"), "gin");

                    b.HasIndex("ResumeId")
                        .IsUnique();

                    b.HasIndex("Score");

                    b.HasIndex("Skills");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Skills"), "gin");

                    b.ToTable("resume_analysis", (string)null);
                });

            modelBuilder.Entity("SmartResumeAnalyzerAgent.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SmartResumeAnalyzerAgent.Domain.Entities.Resume", b =>
                {
                    b.HasOne("SmartResumeAnalyzerAgent.Domain.Entities.User", "User")
                        .WithMany("Resumes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartResumeAnalyzerAgent.Domain.Entities.ResumeAnalysis", b =>
                {
                    b.HasOne("SmartResumeAnalyzerAgent.Domain.Entities.Resume", "Resume")
                        .WithOne("Analysis")
                        .HasForeignKey("SmartResumeAnalyzerAgent.Domain.Entities.ResumeAnalysis", "ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("SmartResumeAnalyzerAgent.Domain.Entities.Resume", b =>
                {
                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("SmartResumeAnalyzerAgent.Domain.Entities.User", b =>
                {
                    b.Navigation("Resumes");
                });
#pragma warning restore 612, 618
        }
    }
}
